#!/bin/bash

WHERE="$1"

[ -z "$WHERE" ] && {
    echo "Syntax: `basename $0` <directory>" >&2
    exit 1
}

cd "$WHERE" || {
    echo " !! Could not cd to dir $WHERE, aborting." >&2
    exit 1
}

echo " -- Searching BOM in *.php files..."

find "./" -type f -name |
while read file
do
    if [ "`head -c 3 -- "$file"`" = $'\xef\xbb\xbf' ]
    then
        echo "found BOM in: $file"
    fi
done

